source 'https://rubygems.org'
ruby '2.0.0'

gem 'dashing'
gem 'fitgem'
gem 'haml'
gem "sass", :require => 'sass'
gem 'sinatra_cyclist'
gem 'octranspo_fetch', '>= 0.0.4'
gem 'newrelic_rpm'
gem 'omniauth-google-apps'
gem 'unicorn'